### ISSUE TITLE
Inconsistencies 

### ISSUE THREAD

**Issue by sg86-** [kakaroto/RCOMage#1]
Hello again, i was pulling my hair out trying to find something in the XMB, thought i was going mad when i realised a plugin didnt extract fully. 'explore_plugin_full.rco'

After trying it again it seemed to extract all of it, i did my edits and compiled to get all images on the XMB missing, and info boxes plain white?

Is there something going on here with image compression that i can check for you.

Note: i am using 1.1.1b a windows GUI, is this nothing to do with you?

**Comment by zingaburga** [comment]
Hi there,
Are you saying that all the images become white on the XMB?

If so, could you try dumping this compiled RCO and see if the images look fine?
I've know that, on the PSP, sometimes images will turn into white blocks if the device is out of memory.  If this is the case, you can try reducing the amount of memory the images consume (reduce resolution and/or bit-depth).

**Comment by kakaroto** [comment]
Hi,
I've been told that the released version has that bug, but the version in this git repository doesn't (at least, not on linux). Maybe you should compile it yourself and see if it fixes it.

**Comment by sg86-** [comment]
yea you are both right, the images on the XMB are all white, but i havent edited them ?

i have compiled 4 .rcos and they are all fine, it was just this one 'explore_plugin_full'

I tried to compile with cygwin, but it fails...

i can compile in linux but i dont really want to use the command line tool, due to the amount of editing i need to do

any help on compiling with cygwin would be great? ive tried following his readme

**Comment by zingaburga** [comment]
Really late, but maybe you might want to start reading from here - perhaps this is the issue.
http://endlessparadigm.com/forum/showthread.php?tid=19501&pid=350549#pid350549
